### PR TITLE
upgrade to hy-0.13.0

### LINKED ISSUE #3: It cannot run in hy-0.11.0

### LINKED ISSUE #4: Upgrade to a later version of Hy
tryhy should use either the latest stable release or GitHub master. Right now it's running Hy 0.10.1, which is neither.

### PR DESCRIPTION
**Pull request by proppy**
Closes #1 
Closes #2 
Closes #3 
Closes #4 
Staged at: http://v13.try-hy.appspot.com/

/cc @Kodiologist

### CODE REVIEW

**Comment by Kodiologist** [comment]
Thanks for working on this!

The REPL seems to hang after I enter a second input.

I see that it's using Python 2; would it be possible to upgrade to Python 3?

**Comment by proppy** [comment]
@Kodiologist fixed the typo.

Sadly the standard "App Engine" environment only support python 2.7, see:
https://cloud.google.com/appengine/docs/python/

**Review by Kodiologist — APPROVED** [review]

**Comment by Kodiologist** [comment]
> Sadly the standard "App Engine" environment only support python 2.7

I was afraid of that. Since you work for Google, you might prod the developers to add support for Python 3. It's 2017, after all.

**Comment by proppy** [comment]
@Kodiologist Thanks for the quick review.

http://try-hy.appspot.com/ is now updated with the `v13` version.

> I was afraid of that. Since you work for Google, you might prod the developers to add support for Python 3. It's 2017, after all.

Google App Engine does support Python 3 thru the [flex environment](https://cloud.google.com/appengine/docs/flexible/python/), but I was afraid that the overhead of GCE VMs might not be justified for a simple application like `try-hy`.

If you feel strongly that the site would benefit from `Python 3`, I'd be happy to give it a try.

**Comment by Kodiologist** [comment]
I'm sorry; I think the CSS changes that you made after I looked at the result broke this on Firefox. [Screenshot.](https://i.imgur.com/UOhBZo5.png)

> If you feel strongly that the site would benefit from Python 3, I'd be happy to give it a try.

It'd be nice, but it's not the most important thing.

**Comment by proppy** [comment]
@Kodiologist can you make sure you cleared up the cache?

hy-firefox

**Comment by Kodiologist** [comment]
I cleared the cache and that didn't fix it, but I waited a bit and cleared it again and now it does. I think the server was taking a bit to update. Thanks again!

**Comment by proppy** [comment]
@Kodiologist Thanks for the nudge, and sorry it took so long.

Say "hy" to @paultag  :)

**Pull request merged**
